name: Simple Docker Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build yelb-ui image
        run: |
          docker build -t yelb-ui:latest ./yelb-ui

      # - name: Build yelb-db image
      #   run: |
      #     docker build -t yelb-db:latest ./yelb-db
