name: Simple Docker Build
on:
  # push:
  #   branches: [master]
  # pull_request:
  #   branches: [master]
  workflow_dispatch:

 
    
jobs:
  build:
    runs-on: tag3
    steps:


     #Build Docker images#
     - name: Build yelb-ui Docker image
       run: |
          docker build --no-cache -t yelb-appserver:latest ./yelb-appserver 
          docker build -t yelb-ui:latest ./yelb-ui 
          docker build -t yelb-db:latest ./yelb-db 
    # # Step 1: Checkout repository code
    # - name: Checkout repository
    #   uses: actions/checkout@v2
    # - name: docker-compose up
    #   run: |
    #       cd /home/fs-lp-27/actions-runner3/_work/yelb/yelb/deployments/localtest
    #       docker-compose -f docker-compose.yaml up -d





          




      
