name: Simple Docker Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: tag1
    steps:
      - name: Run docker-compose up
        run: docker-compose -f deployments/localtest/docker-compose.yaml up -d



   


      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      # - name: Checkout repository
      #   uses: actions/checkout@v3

      # - name: Build yelb-ui Docker image
      #   run: |
      #     docker build -t yelb-ui:latest ./yelb-ui
          
      # - name: Build yelb-db Docker image
      #   run: |
      #     docker build -t yelb-db:latest ./yelb-db
          
      # - name: Build yelb-db Docker image
      #   run: |
      #     docker build -t yelb-db:latest ./yelb-appserver
          
      # - name: List Docker images
      #   run: |
      #      docker images

      # - name: Set up Docker Scout
      #   run: |
      #     docker scout version || echo "Scout CLI is pre-bundled in Docker CLI >= v23.0"
          
      # - name: Scan yelb-ui for vulnerabilities with Docker Scout
      #   run: docker scout cves yelb-ui:latest

      # - name: Scan yelb-db for vulnerabilities with Docker Scout
      #   run: docker scout cves yelb-db:latest

      # - name: Scan yelb-db for vulnerabilities with Docker Scout
      #   run: docker scout cves yelb-appserver:latest

      # - name: Build and start services
      #   run: docker-compose up -d --build

      # - name: Check running containers
      #   run: docker ps -a
        
      # - name: Lint yelb-db Dockerfile
      #   run: hadolint ./yelb-ui/Dockerfile

      # - name: Lint yelb-ui Dockerfile
      #   run: hadolint ./yelb-db/Dockerfile

        















          






