name: Simple Docker Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: tag1
    steps:
    #Dockerhub credentials#
    
       - name: Log in to Docker Hub
         uses: docker/login-action@v3
         with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

       # - name: Set up Docker Scout
       #   run: |
       #      docker scout version || echo "Scout CLI is pre-bundled in Docker CLI >= v23.0"
            
     #Build Docker images#
          
      
       # - name: Build yelb-ui Docker image
       #   run: |
       #    docker build -t yelb-ui:latest ./yelb-ui
       #    docker build -t yelb-db:latest ./yelb-db
       #    docker build -t yelb-appserver:latest ./yelb-appserver
           
          
       - name: List Docker images
         run: |
            docker images
    #Scan Docker images using Docker scout#
          
       # - name: Scan yelb-ui for vulnerabilities with Docker Scout
       #   run: |
       #      docker scout cves yelb-ui:latest
       #      docker scout cves yelb-db:latest
       #      docker scout cves yelb-appserver:latest

      #Scan Docker images using hadolint#
       - name: Scan docker images for Docker hadolint
         run:  |
            hadolint ./yelb-ui/Dockerfile --ignore DL4000
            hadolint ./yelb-db/Dockerfile --ignore DL4000
            hadolint ./yelb-app-server/Dockerfile --ignore DL4000

        #Build the applictaion using docker-compose#
       - name: Run docker-compose up
         run: docker-compose -f deployments/localtest/docker-compose.yaml up -d

        #Slack Integration#

       - name: Notify Slack on success
         if: success()
         run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"✅ Build succeeded on GitHub Actions!"}' \
          ${{ secrets.SLACK_WEBHOOK_URL }}

       - name: Notify Slack on failure
         if: failure()
         run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"❌ Build failed on GitHub Actions."}' \
          ${{ secrets.SLACK_WEBHOOK_URL }}


        

























          






