name: Simple Docker Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: tag1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # - name: Build yelb-ui Docker image
      #   run: |
      #     docker build -t yelb-ui:latest ./yelb-ui
          
      # - name: Build yelb-db Docker image
      #   run: |
      #     docker build -t yelb-db:latest ./yelb-db
          
      # - name: List Docker images
      #   run: |
      #      docker images

      - name: Set up Docker Scout
        run: |
          docker scout version || echo "Scout CLI is pre-bundled in Docker CLI >= v23.0"

        











          






