name: Simple Docker Build
on:
  # push:
  #   branches: [master]
  # pull_request:
  #   branches: [master]
  workflow_dispatch:
 
    
jobs:
  build:
    runs-on: tag3
    steps:
    # Step 1: Checkout repository code
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: List directory contents
      run: |
          cd /home/fs-lp-27/actions-runner3/_work/yelb/yelb/deployments/localtest
          docker-compose -f docker-compose.yaml up -d
