name: Simple Docker Build
on:
  # push:
  #   branches: [master]
  # pull_request:
  #   branches: [master]
  workflow_dispatch:

 
    
jobs:
  build:
    runs-on: tag3
    steps:
    
     - name: Log in to Docker Hub
       uses: docker/login-action@v3
       with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


     # #Build Docker images#
     # - name: Build yelb-ui Docker image
     #   run: |
     #      docker build --no-cache -t yelb-appserver:latest ./yelb-appserver 
     #      docker build -t yelb-ui:latest ./yelb-ui 
     #      docker build -t yelb-db:latest ./yelb-db 

   
     # - name: Tag Docker image
     #   run: |
     #      docker tag yelb-ui:latest 311141523175.dkr.ecr.us-east-1.amazonaws.com/ecr1:yelb-ui
     #      docker tag yelb-db:latest 311141523175.dkr.ecr.us-east-1.amazonaws.com/ecr1:yelb-db
     #      docker tag yelb-appserver:latest 311141523175.dkr.ecr.us-east-1.amazonaws.com/ecr1:yelb-appserver
          
     - name: Scan yelb-ui for vulnerabilities with Docker Scout
       run: |
            
            docker scout cves yelb-ui:latest > /home/fs-lp-27/actions-runner3/_work/yelb/yelb/yelb-ui-cves.txt
            docker scout cves yelb-db:latest > /home/fs-lp-27/actions-runner3/_work/yelb/yelb/yelb-db-cves.txt
            docker scout cves yelb-appserver:latest > /home/fs-lp-27/actions-runner3/_work/yelb/yelb/yelb-appserver-cves.txt

    
    # # Step 1: Checkout repository code
    # - name: Checkout repository
    #   uses: actions/checkout@v2
    # - name: docker-compose up
    #   run: |
    #       cd /home/fs-lp-27/actions-runner3/_work/yelb/yelb/deployments/localtest
    #       docker-compose -f docker-compose.yaml up -d





          




      
