name: Simple Docker Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


jobs:
  build:
    runs-on: tag1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build yelb-ui Docker image
        run: |
          docker build -t yelb-ui:latest ./yelb-ui







          






